[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExpressionTreeForge = "93090adf-0e31-445f-8c8f-44d91f61d7ad"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Documenter = "1"
JuMP = "1"
MathOptInterface = "1"
Symbolics = "7"
